<?php
declare(strict_types=1);

final class Database
{
    private static ?PDO $connection = null;

    public static function connect(): PDO
    {
        if (self::$connection !== null) return self::$connection;
        $c = require dirname(__DIR__) . '/config.php';
        foreach (['host', 'port', 'name', 'sslmode'] as $key) {
            if (!preg_match('/^[a-zA-Z0-9_.-]+$/', (string)$c[$key])) {
                throw new RuntimeException('Configuração inválida: ' . $key);
            }
        }
        $base = "pgsql:host={$c['host']};port={$c['port']};dbname={$c['name']};sslmode={$c['sslmode']}";
        $options = [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false];
        $pdo = new PDO($base, $c['user'], $c['password'], $options);
        $pdo->exec('CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_salt CHAR(32) NOT NULL, password_hash CHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)');
        $pdo->exec('CREATE TABLE IF NOT EXISTS suppliers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(190), phone VARCHAR(30), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)');
        $pdo->exec('CREATE TABLE IF NOT EXISTS products (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id INTEGER NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT, name VARCHAR(160) NOT NULL, description TEXT, price NUMERIC(10,2) NOT NULL CHECK (price >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)');
        $pdo->exec('CREATE TABLE IF NOT EXISTS baskets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)');
        $pdo->exec('CREATE TABLE IF NOT EXISTS basket_items (basket_id INTEGER NOT NULL REFERENCES baskets(id) ON DELETE CASCADE, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE, PRIMARY KEY (basket_id, product_id))');
        return self::$connection = $pdo;
    }
}
